# SD212: Graph Learning

# Sparse Matrices

In this lab, you will learn to use sparse matrices.

In [352]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [353]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [354]:
X_dense

array([[2, 1, 2, 0, 0],
       [1, 1, 0, 1, 2],
       [2, 2, 1, 0, 2],
       [0, 0, 1, 2, 2],
       [2, 0, 0, 2, 2],
       [2, 2, 0, 2, 1],
       [2, 1, 2, 0, 1],
       [1, 2, 0, 2, 1],
       [1, 0, 1, 1, 2],
       [2, 2, 1, 1, 2]])

In [355]:
X_csr = sparse.csr_matrix(X_dense)

In [356]:
X_csr.shape

(10, 5)

In [357]:
# number of non-zeros
X_csr.nnz

38

The data structure consists of 3 vectors:

In [358]:
X_csr.indices

array([0, 1, 2, 0, 1, 3, 4, 0, 1, 2, 4, 2, 3, 4, 0, 3, 4, 0, 1, 3, 4, 0,
       1, 2, 4, 0, 1, 3, 4, 0, 2, 3, 4, 0, 1, 2, 3, 4])

In [359]:
X_csr.indptr

array([ 0,  3,  7, 11, 14, 17, 21, 25, 29, 33, 38])

In [360]:
X_csr.data

array([2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2], dtype=int32)

## To do

* Can you find the number of non-zeros from these 3 vectors?

* What about the shape of the matrix?

### Answers

*  Yes, from the las item of X_csr.indptr

* The length of the X_csr.indptr vector minus 1 gives you the number of rows in the matrix.

The length of the X_csr.indices vector gives you the number of non-zero elements in the matrix.

The number of columns in the matrix can be determined by finding the maximum value in the X_csr.indices vector and adding one (since indices start from zero)



In [361]:
last_value = X_csr.indptr[-1]
print("Last value of X_csr.indptr:", last_value)


num_rows = len(X_csr.indptr) - 1
num_nonzero_elements = len(X_csr.indices)
num_cols = max(X_csr.indices) + 1

print("Shape of the matrix:", (num_rows, num_cols))
print("Number of non-zero elements:", num_nonzero_elements)

Last value of X_csr.indptr: 38
Shape of the matrix: (10, 5)
Number of non-zero elements: 38


## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [362]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [363]:
X_dense

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 0, 1]])

In [364]:
a = np.ones(n_col, dtype=int)

In [365]:
b = X.dot(a)

In [366]:
b

array([2, 2, 0, 2, 1, 4, 3, 2, 3, 3], dtype=int32)

In [367]:
b.shape

(10,)

In [368]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [369]:
b

array([5, 8, 3, 6], dtype=int32)

In [370]:
b.shape

(4,)

In [371]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [372]:
A

array([[1, 0],
       [0, 0],
       [0, 1],
       [1, 0]])

In [373]:
B

array([[1, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [2, 1],
       [1, 1],
       [1, 1],
       [2, 0],
       [2, 0]], dtype=int32)

In [374]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [375]:
B

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 11 stored elements in Compressed Sparse Row format>

In [376]:
B.toarray()

array([[1, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [2, 1],
       [1, 1],
       [1, 1],
       [2, 0],
       [2, 0]], dtype=int32)

In [377]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Column format>

In [378]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.intc'>'
	with 77 stored elements in Compressed Sparse Row format>

In [379]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [380]:
X

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 34 stored elements in Compressed Sparse Row format>

In [381]:
Y = X > 1

In [382]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 22 stored elements in Compressed Sparse Row format>

In [383]:
Y.dot(np.ones(n_col, dtype=int))

array([3, 2, 0, 1, 1, 3, 4, 3, 2, 3], dtype=int32)

In [384]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [385]:
Z = 2 * X + 5 * Y

In [386]:
Z

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 34 stored elements in Compressed Sparse Row format>

In [387]:
Z.power(2)

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 34 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [388]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

In [389]:
import numpy as np
from scipy.sparse import linalg

norms = linalg.norm(X, axis=1)
print(norms)

[3.         3.         1.73205081 3.         2.82842712 1.41421356
 1.73205081 1.73205081 1.         3.16227766 1.41421356 2.44948974
 2.44948974 2.82842712 1.73205081 1.         1.         3.
 2.         2.        ]


## Slicing

Sparse matrices can be sliced like numpy arrays.

In [390]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [391]:
X = sparse.csr_matrix(X_dense)

In [392]:
indices = [2, 5, 6]

In [393]:
X[indices]

<3x5 sparse matrix of type '<class 'numpy.intc'>'
	with 10 stored elements in Compressed Sparse Row format>

In [394]:
X[:, [1, 3]]

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Row format>

## To do 

Consider the following matrix:

In [395]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

## DIAG format

In [396]:
D = sparse.diags(np.arange(10))

In [397]:
D

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>

In [398]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [399]:
D.nnz

10

In [400]:
D = sparse.csr_matrix(D)

In [401]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [402]:
D.nnz

9

In [403]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [404]:
D.dot(X)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [405]:
D = sparse.diags(np.ones(4))

In [406]:
X.dot(D)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 18 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [407]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [408]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [409]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [410]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [411]:
X_coo.row

array([1, 4, 2])

In [412]:
X_coo.col

array([2, 0, 2])

In [413]:
X_coo.data

array([1, 2, 3])

You can change the format:

In [414]:
X_csr = X_coo.tocsr()

In [415]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [416]:
X_csr.indices

array([2, 2, 0])

In [417]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3])

In [418]:
X_csr.data

array([1, 3, 2], dtype=int32)

In [419]:
X_csr.tocoo()

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in COOrdinate format>

You can directly load a CSR matrix from COO format:

In [420]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [421]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

Duplicate entries are not summed by default in the COO format (also in the CSR format in the last version of Scipy):

In [422]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [423]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [424]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [425]:
X_coo.nnz

4

In [426]:
X_coo.toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0]])

In [427]:
X_coo.dot(np.ones(5, dtype=int))

array([0, 5, 3, 0, 2], dtype=int32)

In [428]:
X_coo.data

array([1, 2, 3, 4])

In [429]:
X_coo.sum_duplicates()

In [430]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [431]:
X_coo.data

array([5, 3, 2])

If data contain some zeros, these are coded as non-zeros by default:

In [432]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 0]

In [433]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [434]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [435]:
X_csr.eliminate_zeros()

In [436]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [437]:
row = [1, 1, 2, 4, 2, 1]
col = [2, 2, 2, 0, 2, 2]
data = [1, 2, 3, 4, 0, 2]

X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))
X_csr.sum_duplicates()

* What is the number of non-zeros? 
* Check your answer using ``nnz``.